### ISSUE TITLE
Use respimagelint with modern tooling

### ISSUE THREAD

**Issue by AurelioDeRosa** [ausi/respimagelint#14]
Hi.

The idea of this linter is interesting and I'd like to try it on a wider range of pages. To do that, automation is crucial, so I'm opening this issue to suggest its integration with some tools such as PhantomJS.

**Comment by ausi** [comment]
Thank you for your feedback, there is already issue #10 *“Think of creating a node/gulp/grunt plugin”*. It would be great if you could comment there how you think such an integration should look like or what it should provide from your perspective.

**Comment by AurelioDeRosa** [comment]
Sorry, I completely missed it. I'm going to comment in the other issue.
