### ISSUE TITLE
linter seems to be misinterpreting vh as vw

### ISSUE THREAD

**Issue by AMA3** [ausi/respimagelint#20]
Given this code:

```
<!DOCTYPE html>
<html>
<body>
<style>
#CONT {
  margin: 0 auto;
  position: relative;
  overflow: hidden;
  max-width: 110vh;
  }
img, picture {
  width: 100%;
  height: auto;
  }
</style>
<div id=CONT >
<picture>
	<source
		media="(orientation:portrait) and (max-width:440px)"
		sizes="100vw" srcset="p44/easter-hunt-1-1433369.jpg 440w" >
	<img
		src="100/easter-hunt-1-1433369.jpg" alt=""
		sizes="(max-width:110vh) 100vw, 110vh"
		srcset="200/easter-hunt-1-1433369.jpg 2000w,
			100/easter-hunt-1-1433369.jpg 1000w,
			50/easter-hunt-1-1433369.jpg 500w,
			25/easter-hunt-1-1433369.jpg 250w" >
</picture>
</div>
</body>
</html>
```

I get this message:

> The size of the image doesn’t match the sizes attribute (max-width: 110vh) 100vw, 110vh. At a viewport width of 1280 the image was 875 pixels wide instead of the specified 1408 (-38% difference). The affected viewport widths are 300-3000.

It seems that the linter is misinterpreting 110vh as 100vw because 1408 = 1280*110%.

**Comment by AMA3** [comment]
BTW, this still happens when I add:

```
@media only all and (orientation:portrait) and (max-width:440px) {
  #CONT {
    max-width: 100vw;
    }
}
```

to the stylesheet.

**Comment by ausi** [comment]
You are right, `vh`, `vmin` and `vmax` did get interpreted as `vw`. Also `orientation` media queries were not supported.

Should be fixed now.

**Comment by AMA3** [comment]
Thanks!  Do you accept donations?

**Comment by ausi** [comment]
Yes, I do :) <https://salt.bountysource.com/checkout/amount?team=respimagelint>

**Comment by ausi** [comment]
@AMA3 You can now support my open source work on Patreon: [patreon.com/ausi](https://www.patreon.com/ausi)
