### ISSUE TITLE
Shopify support

### ISSUE THREAD

**Issue by ekwoka** [ausi/respimagelint#39]
Oddly, when trying to run this on a shopify store, an error is served saying that it failed to load the page in an iframe.

Tested on latest chromium edge and chrome. Same result.

This would be massively helpful if this could be solved.

**Comment by ausi** [comment]
Shopify uses the HTTP header `X-Frame-Options: deny` (for security reasons) which makes it impossible to load the page in an iframe.

To overcome these issues I have to rewrite the bookmarklet as a browser dev tools extension I think. See https://github.com/ausi/respimagelint/issues/10#issuecomment-616762862

**Comment by baldurh** [comment]
Old thread, but just wanted to note that you can just fire up a simple local proxy on your machine and run the script on the proxied page.

eg. something like:
```python
from http.server import SimpleHTTPRequestHandler
import socketserver
from urllib import request

PORT = 9097
class MyProxy(SimpleHTTPRequestHandler):
    def do_GET(self):
        url=self.path[1:]
        self.send_response(200)
        self.end_headers()
        self.copyfile(request.urlopen(url), self.wfile)
httpd = socketserver.ForkingTCPServer(('', PORT), MyProxy)
print("Now serving at", str(PORT))
httpd.serve_forever()
```

Run it like so:
`python proxy.py`

then access it in your browser like so:
`http://localhost:9097/https://yourshop.com`

works like a charm
