### ISSUE TITLE
Chromium: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by kopax** [ausi/respimagelint#46]
I've added the bookmark, on my localhost website, I have run the script.

```bash
store.js:2 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://ausi.github.io/respimagelint/store.js:2:60
```

I am using chromium, any clue what I am doing wrong here?

**Comment by ausi** [comment]
I think you have to disable the “Block third-party cookies and site data” checkbox to fix this, see: https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by kopax** [comment]
That was it, Now I can see the result and it's exactly the tool I was looking for so I can get started with responsive images. Thanks a lot for sharing this !
