### ISSUE TITLE
Filter report page to only failed checks

### ISSUE THREAD

**Issue by danielbachhuber** [ausi/respimagelint#63]
When a report page has dozens of checks, it can be difficult to find the failed ones.

It would be nice to have a simple filter to limit the report to only failed checks.

**Comment by ausi** [comment]
With a1a63d05a26b5fc3ba17b9de1d4a52fc9598d46f images with failed checks are now shown first.

**Comment by danielbachhuber** [comment]
I saw this change in action earlier today 😄 

From my perspective, it was a little unexpected to have the images appear out of order.

What if the images remained in order, but there was a button at the top to "Only show failed checks"? Clicking on the button once would hide the successful checks. Clicking on the button again would show the successful checks again. If there weren't any failed checks, the button would not appear.

**Comment by danielbachhuber** [comment]
Also, not to shove too many things on this issue 😄 ... it would be nice to have a total count of passed and failed checks at the top.

**Comment by ausi** [comment]
Fixed in 12fc9f0cd1e9aed2d8dafe4446a79f958a09e6ad

**Comment by danielbachhuber** [comment]
Love it!

<img width="604" alt="image" src="https://user-images.githubusercontent.com/36432/150331133-ef6e08e6-e48c-44fb-a3e5-30c25e9110d5.png">
