### ISSUE TITLE
Round suggested 'srcset' values to nearest 10

### ISSUE THREAD

**Issue by danielbachhuber** [ausi/respimagelint#67]
From https://github.com/ausi/respimagelint/issues/62#issuecomment-1017420736

> Also, what do you think about rounding the suggestions to the closest 10 (e.g. 268 -> 270)? I feel like it might be a little more human-friendly.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/36432/150531187-455ab298-b9c1-4261-91df-f85f630851e3.png">

**Comment by danielbachhuber** [comment]
Right now, I'm rounding up in my head, which works well enough.

**Comment by ausi** [comment]
Added rounding in 2905e4a1bd1e87f9f1d50f91c98f582b770c57f6
