### ISSUE TITLE
Acknowledge existing 'srcset' values when providing suggested 'srcset' values

### ISSUE THREAD

**Issue by danielbachhuber** [ausi/respimagelint#68]
Given the following example:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/36432/150543153-f87b2ae5-8296-41a7-9f61-19248ccb8d82.png">

It would be helpful if the bookmarklet acknowledged the `srcset` values that already existed, when providing suggested `srcset` values. Of the suggested values, I think I only need to create something in the ~450 range?

**Comment by ausi** [comment]
Implemented in 9d1c6d8ceb9eca396c50abf21d47aa5420e16bce
