### ISSUE TITLE
problem responive image wordpress single blog featured image + content image

### ISSUE THREAD

**Issue by socialreza** [ausi/respimagelint#76]
ln single blog, the width is 100% columnless and the width of the content box is 1200 pixels.

the sizes suggested by the responsive image linter for single blog content image (1920x1080)(width 1098px) : 256x144 + 1094x615 + 1560x878 + 1920x1080 + 2028x1152, pagespeed "properly size images" in mobile 1094x615 for single blog content image

the sizes suggested by the responsive image linter for single blog featured image (1920x1080)(width 1118px) : 280x158 + 1118x629 + 1570x883 + 1920x1080 + 2028x1152, pagespeed "properly size images" in mobile 1118x629 for single blog featured image

**Comment by ausi** [comment]
Im not sure I can follow your description.

What is the error, or what do you think did the linter report incorrectly?

Can you post the URL to the affected website?

**Comment by socialreza** [comment]
thanks for the quick reply, the distance between 256x144 and 1094x615 is so large, that it is possible to put another size between the two that does not have to load 1094x615 in mobile mode. this should be the case for 280x158 and 1118x629 as well.
in pagespeed google in mobile mode, we encounter an error "properly size images" that says the size is not suitable for mobile , Because 1094x615 and 1118x629 sizes are loaded in mobile phones

**Comment by ausi** [comment]
This is probably the same issue as described in https://github.com/ausi/respimagelint/issues/70#issuecomment-1026222380 is it?

**Comment by socialreza** [comment]
as i understand it, you are saying that most mobile phones are between 360 and 375, and since their screen quality is high, it is better to load high-quality photos, right? now my blog page is 3 columns, between size 365x205 and 1170x658, a size of 730x411 has been suggested by "Linter for Responsive Images", but this size is not suggested in a single blog that is 100 width, what is the reason?

**Comment by ausi** [comment]
> you are saying that most mobile phones are between 360 and 375

Yes, and as you said “in pagespeed google in mobile mode, we encounter an error” is probably because they use a width of 360 and our linter is not yet optimized for that width.

To debug your example I’d need a link to the affected webpage.
How the suggestion algorithm works is described in https://github.com/ausi/respimagelint/issues/62#issuecomment-1018556187
