### ISSUE TITLE
Issue with computation of "specified" width

### ISSUE THREAD

**Issue by nhoizey** [ausi/respimagelint#77]
I'm using the bookmarklet on https://nicolas-hoizey.com where I saw I had wrong sizes attribute values.

For the first image (my face 😅), I get this:
![image](https://user-images.githubusercontent.com/78213/178605020-7422c4bb-84e9-4cff-9113-f6654a45d7c0.png)

It says "The size of the image doesn’t match the `sizes` attribute `(min-width: 66.7rem) 14.4rem, (min-width: 30rem) calc(22.5vw - .6rem), (min-width: 20rem) calc(30vw - .6rem), calc(45vw - .6rem)`. At a viewport of 1280x720 the image was 230.2 pixels wide instead of the specified 276 (-17% difference)."

"At a viewport of 1280x720" -> `min-width: 66.7rem` applies and the image width should be `14.4rem` -> `230.4px` with `1rem` = `16rem` (as I checked in my browser's settings)

So the reported "230.2 pixels" look great IMHO, and I don't understand where "the specified 276" comes from.

The other images in the page seem to have the same issue.

**Comment by ausi** [comment]
The linter wasn’t able to interpret `rem` values correctly. Should be fixed now.

**Comment by nhoizey** [comment]
@ausi it work now indeed, thanks! 🙏
