### ISSUE TITLE
JS error on https://ausi.github.io/respimagelint/linter.html

### ISSUE THREAD

**Issue by DeeJ** [ausi/respimagelint#78]
`Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    [114]< https://ausi.github.io/respimagelint/linter.js:347
    o https://ausi.github.io/respimagelint/linter.js:1
    r https://ausi.github.io/respimagelint/linter.js:1
    <anonymous> https://ausi.github.io/respimagelint/linter.js:1
`

**Comment by ausi** [comment]
Possibly a duplicate of #75 ?

**Comment by ausi** [comment]
Should be fixed since 194f75598b0fc0e26bb3166a17a3e5ecbb25f30b if the issue still appears please open a new issue.
