### ISSUE TITLE
properly size images problem again

### ISSUE THREAD

**Issue by socialreza** [ausi/respimagelint#82]
i scanned the single blog, this page is full width and its featured image is also full width

280×158 1118×629 1570×883 1920×1080 2048×1152

sizes="(min-width: 1200px) 1118px, 95.45vw"

but the error i get properly sized images in mobile pagespeed : 1118x629.jpg

i'm very picky about making images responsive

**Comment by ausi** [comment]
This could probably be solved by https://github.com/ausi/respimagelint/issues/70#issuecomment-1026222380
