### ISSUE TITLE
Arc Browser Support or alternative way to execute linting

### ISSUE THREAD

**Issue by peter-neumann-dev** [ausi/respimagelint#84]
In my Arc browser, the linting from a bookmark does nothing. It is switching to a blank page instead of executing on the current page.

Is there a way to execute the linter from DevTools or the console as a workaround?

Browser: [https://thebrowser.company/](https://thebrowser.company/) (based on chromium)
[ I can invite one developer with my personal gift code to test if necessary ]

**Comment by peter-neumann-dev** [comment]
Thank you @ausi! I will dive into the browser settings to see if there is something different to Chrome.

For now, I have found a workaround of execution it from the console without having to leave the Browser:

```javascript
(function(){!function(){var e=document.createElement("script");e.id="respimagelint-script",e.type="text/javascript",e.src="https://ausi.github.io/respimagelint/collector.js?"+Date.now(),document.body.appendChild(e)}();})()
```

**Additional tip:** I have created a snipped with Raycast, so I can just type `imglint` and it will paste it for me

**Comment by peter-neumann-dev** [comment]
Arc Browser does not support Bookmarklets because it's not saving favorites because they are only pinned tabs.

I have created a [Chrome extension](https://github.com/peter-neumann-dev/responsive-image-linter) that is doing what I described above. This will solve it for me for now 🙂

**Comment by ausi** [comment]
Awesome! ❤️

Will try to take a look at your chrome extension, maybe it would make sense to link to it from the readme of this project...

**Comment by peter-neumann-dev** [comment]
It works, but it's a hard forked version of the minified JS that I adjusted slightly to make it work. I think if there will be more changes to your GitHub page in the future, it will break, and I have to adjust that again.

It can be improved, but for now, it was a quick solution for me 😃
