### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by GaetanRedoutez** [ausi/respimagelint#91]
Hello, 
When i'm using the bookmark the actual result is totaly white like this : 
![image](https://github.com/ausi/respimagelint/assets/144777750/6cffa80e-f168-443a-bd44-2ac25093b1bd)
Can you help me ?

**Comment by Nasirahamad88** [comment]
Can you tell me more?

**Comment by GaetanRedoutez** [comment]
Maybe better with the error, when i run on my site, with the bookmark and extension i've a console error : 
linter.js:467 Uncaught TypeError: Cannot read properties of undefined (reading 'fixed')
    at linter.js:467:750
    at Array.map (<anonymous>)
    at computeSizesAttribute (linter.js:467:724)
    at linter.js:369:376
    at Array.forEach (<anonymous>)
    at exports.default (linter.js:369:127)
    at exports.default (linter.js:355:349)
    at linter.js:424:192
    at Array.forEach (<anonymous>)
    at exports.default (linter.js:424:147)

**Comment by ausi** [comment]
Does the error also occur if you use the browser extension? https://chrome.google.com/webstore/detail/responsive-image-linter/mnddginionlghpblkimpdalcecpnbjln

**Comment by GaetanRedoutez** [comment]
Yes exactly the same,

**Comment by ausi** [comment]
We probably need to add a check if `currentRage` is `undefined` here: https://github.com/ausi/respimagelint/blob/194f75598b0fc0e26bb3166a17a3e5ecbb25f30b/src/util/computeSizesAttribute.js#L57-L58

**Comment by Harizriz** [comment]
I'm currently facing the same issue. May I know when this PR https://github.com/ausi/respimagelint/pull/94 can be merged?
